### ISSUE TITLE
UnboundLocalError: local variable 'most_recent_record' referenced before assignment

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#59]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/dear_petition/petition/views.py", line 38, in create_petition
    output = form.save()
  File "/app/dear_petition/petition/forms.py", line 97, in save
    petition = Writer(form_data, self.batch, template_path, output)
  File "/app/dear_petition/petition/writer.py", line 19, in __init__
    self.data = map_data(form_data, batch)
  File "/app/dear_petition/petition/data_dict.py", line 8, in map_data
    record = batch.most_recent_record
  File "/app/dear_petition/petition/models.py", line 141, in most_recent_record
    return most_recent_record
UnboundLocalError: local variable 'most_recent_record' referenced before assignment
```

**Comment by georgehelman** [comment]
This will be more involved that I at first thought. This is happening because this record has an Offense Date field rather than an Offense Date/Time, which is what the parser expects.

At this point, I think we need more robust parsing so that the app won't error out whenever it sees something it doesn't expect. Users also need to be able to manually override the parsed fields in the petition generator form so that it's not a fail case when the parsers don't parse as expected. I opened an issue for that. Once we have those things, this one will be solved for free. I'll try to work on those things before next meeting.

**Comment by copelco** [comment]
Is it possible to edit the petition PDF after it's been generated. Would that solve the "override" case?

**Comment by georgehelman** [comment]
That does solve it for now, but I still hold out hope that one day we can figure out how to render a PDF directly rather than the FDF. I think that will be necessary to make it behave consistently across browsers. I was thinking we could add form fields similar to the ones we already have for the attorney fields.
